name: walkscape
description: "WalkscapE dependencies"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Maps / Geo
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  maplibre_gl: ^0.22.0
  geolocator: ^14.0.2
  gpx: ^2.3.0
  turf: ^0.0.10

  # Permissions / Sensors
  permission_handler: ^12.0.1
  sensors_plus: ^6.1.2

  # State / Navigation
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1

  # Codegen / JSON
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Storage / Files / Sharing
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  share_plus: ^11.1.0

  # Config
  flutter_dotenv: ^6.0.0
  in_app_purchase: ^3.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
